// Restore January 2026 Daily Accomplishment records from the verified
// historical inspection output.
//
// Run from the project root:
//   flutter test test/restore_january_2026.dart
//
// This uses the app's own repository.save() path rather than writing SQLite
// columns directly, so the current database schema/serialization remains authoritative.

import 'package:flutter_test/flutter_test.dart';

import 'package:mpor_ipcr_flutter/features/daily_accomplishment/data/daily_accomplishment_repository.dart';
import 'package:mpor_ipcr_flutter/features/daily_accomplishment/domain/daily_accomplishment_record.dart';

void main() {
  test('Restore January 2026 Daily Accomplishment records', () async {
    final records = <DailyAccomplishmentRecord>[

      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-01'),
        status: DailyAccomplishmentStatus.holiday,
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: true,
        dutyStatusReason: 'Holiday / Non-Working Day',
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-02'),
        status: DailyAccomplishmentStatus.holiday,
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: true,
        dutyStatusReason: 'Holiday / Non-Working Day',
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-05'),
        servedClients: 0,
        installValidatePin: 1,
        checkedPin: 0,
        updatePropertyIndexMaps: 6,
        updateTaxMapControlRolls: 2,
        updateMunicipalDigitalBaseMaps: 6,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-06'),
        servedClients: 0,
        installValidatePin: 8,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 1,
        updateMunicipalDigitalBaseMaps: 1,
        plotTechnicalDescription: 3,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 2,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-07'),
        servedClients: 0,
        installValidatePin: 2,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 17,
        plotTechnicalDescription: 8,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-08'),
        servedClients: 0,
        installValidatePin: 4,
        checkedPin: 0,
        updatePropertyIndexMaps: 2,
        updateTaxMapControlRolls: 4,
        updateMunicipalDigitalBaseMaps: 2,
        plotTechnicalDescription: 2,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-09'),
        status: DailyAccomplishmentStatus.leave,
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: true,
        dutyStatusReason: 'Leave',
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-12'),
        servedClients: 0,
        installValidatePin: 3,
        checkedPin: 0,
        updatePropertyIndexMaps: 3,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 7,
        plotTechnicalDescription: 3,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-13'),
        servedClients: 0,
        installValidatePin: 13,
        checkedPin: 0,
        updatePropertyIndexMaps: 9,
        updateTaxMapControlRolls: 10,
        updateMunicipalDigitalBaseMaps: 9,
        plotTechnicalDescription: 2,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-14'),
        servedClients: 2,
        installValidatePin: 3,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 3,
        plotTechnicalDescription: 1,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-15'),
        servedClients: 0,
        installValidatePin: 5,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 47,
        plotTechnicalDescription: 34,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-16'),
        status: DailyAccomplishmentStatus.leave,
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: true,
        dutyStatusReason: 'Leave',
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-19'),
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 2,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 25,
        plotTechnicalDescription: 25,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-20'),
        servedClients: 0,
        installValidatePin: 48,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 25,
        updateMunicipalDigitalBaseMaps: 2,
        plotTechnicalDescription: 2,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-21'),
        servedClients: 0,
        installValidatePin: 3,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 3,
        plotTechnicalDescription: 3,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-22'),
        servedClients: 0,
        installValidatePin: 1,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 7,
        updateMunicipalDigitalBaseMaps: 12,
        plotTechnicalDescription: 5,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-23'),
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 1,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 9,
        plotTechnicalDescription: 4,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-26'),
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-27'),
        servedClients: 1,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 54,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-28'),
        servedClients: 0,
        installValidatePin: 7,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 3,
        updateMunicipalDigitalBaseMaps: 3,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-29'),
        servedClients: 0,
        installValidatePin: 8,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 5,
        updateMunicipalDigitalBaseMaps: 44,
        plotTechnicalDescription: 12,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: false,
        dutyStatusReason: null,
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
      DailyAccomplishmentRecord(
        date: DateTime.parse('2026-01-30'),
        status: DailyAccomplishmentStatus.leave,
        servedClients: 0,
        installValidatePin: 0,
        checkedPin: 0,
        updatePropertyIndexMaps: 0,
        updateTaxMapControlRolls: 0,
        updateMunicipalDigitalBaseMaps: 0,
        plotTechnicalDescription: 0,
        preparedDailyTimeRecord: 0,
        submittedMpor: 0,
        submittedIpcr: 0,
        attendedMeetings: 0,
        interveningTasks: 0,
        notRegularDuty: true,
        dutyStatusReason: 'Leave',
        timeIn: null,
        timeOut: null,
        tardinessMinutes: 0,
        undertimeMinutes: 0,
      ),
    ];

    for (final record in records) {
      await dailyAccomplishmentRepository.save(record);
    }

    final restored = await dailyAccomplishmentRepository.getMonth(2026, 1);

    expect(restored.length, 22);

    // Verify the key historical values used by the January report.
    final jan05 = restored.firstWhere((r) => r.date.day == 5);
    expect(jan05.installValidatePin, 1);
    expect(jan05.updatePropertyIndexMaps, 6);
    expect(jan05.updateTaxMapControlRolls, 2);
    expect(jan05.updateMunicipalDigitalBaseMaps, 6);

    final jan15 = restored.firstWhere((r) => r.date.day == 15);
    expect(jan15.installValidatePin, 5);
    expect(jan15.updateMunicipalDigitalBaseMaps, 47);
    expect(jan15.plotTechnicalDescription, 34);

    final jan29 = restored.firstWhere((r) => r.date.day == 29);
    expect(jan29.installValidatePin, 8);
    expect(jan29.updateTaxMapControlRolls, 5);
    expect(jan29.updateMunicipalDigitalBaseMaps, 44);
    expect(jan29.plotTechnicalDescription, 12);

    final jan01 = restored.firstWhere((r) => r.date.day == 1);
    expect(jan01.notRegularDuty, true);
    expect(jan01.dutyStatusReason, 'Holiday / Non-Working Day');

    final jan30 = restored.firstWhere((r) => r.date.day == 30);
    expect(jan30.notRegularDuty, true);
    expect(jan30.dutyStatusReason, 'Leave');

    print('RESTORED: ${restored.length} January 2026 records');
    print('January 2026 database data is back.');
  });
}
